### ISSUE TITLE
Router still flakes

### ISSUE THREAD

**Issue by simo5** [keycloak/openshift-integration#8]
Sometimes the router still gets stuff, I found out that doing the following often works:

oc delete rc router-1
docker stop <kublet container id>
docker start <kublet container id>
oc rollout latest dc/router

But this needs to be resolved so that the demo works consistently.

**Comment by slaskawi** [comment]
I think it happens a bit more often with the latest OCP images (3.10)

**Comment by stianst** [comment]
I haven't seen this. Is it still an issue?
